server:
  port: 10024

spring:
  application:
    name: mock

logging:
  config: classpath:logback-test.xml

kingmeter:
  requestBusiness: false
  business:
    baseUrl : http://127.0.0.1:10013


socket:
  port: 10023


